### ISSUE TITLE
Frontiers paper

### ISSUE THREAD

**Issue by nancyrouleurs** [AutomatedFishID/afid-publications#2]
- [x] Render the new results and wrap up the experiments for the paper.

**Comment by nancyrouleurs** [comment]
...

**Comment by marrabld** [comment]
- [x] Address reviewers comments.
- [x] Upload supplementary images from Nancy
- [x] Resubmit in the portal

**Comment by marrabld** [comment]
Resubmitted.  Hopefully we get a quick turn around

**Comment by nancyrouleurs** [comment]
Closed this issue. The paper got accepted.
